# Generated by Django 5.2 on 2025-04-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0003_remove_usuario_senha_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esq_ombro_x', models.FloatField(blank=True, null=True)),
                ('esq_ombro_y', models.FloatField(blank=True, null=True)),
                ('dir_ombro_x', models.FloatField(blank=True, null=True)),
                ('dir_ombro_y', models.FloatField(blank=True, null=True)),
                ('esq_cotovelo_x', models.FloatField(blank=True, null=True)),
                ('esq_cotovelo_y', models.FloatField(blank=True, null=True)),
                ('dir_cotovelo_x', models.FloatField(blank=True, null=True)),
                ('dir_cotovelo_y', models.FloatField(blank=True, null=True)),
                ('esq_pulso_x', models.FloatField(blank=True, null=True)),
                ('esq_pulso_y', models.FloatField(blank=True, null=True)),
                ('dir_pulso_x', models.FloatField(blank=True, null=True)),
                ('dir_pulso_y', models.FloatField(blank=True, null=True)),
                ('esq_quadril_x', models.FloatField(blank=True, null=True)),
                ('esq_quadril_y', models.FloatField(blank=True, null=True)),
                ('dir_quadril_x', models.FloatField(blank=True, null=True)),
                ('dir_quadril_y', models.FloatField(blank=True, null=True)),
                ('esq_joelho_x', models.FloatField(blank=True, null=True)),
                ('esq_joelho_y', models.FloatField(blank=True, null=True)),
                ('dir_joelho_x', models.FloatField(blank=True, null=True)),
                ('dir_joelho_y', models.FloatField(blank=True, null=True)),
                ('esq_tornozelo_x', models.FloatField(blank=True, null=True)),
                ('esq_tornozelo_y', models.FloatField(blank=True, null=True)),
                ('dir_tornozelo_x', models.FloatField(blank=True, null=True)),
                ('dir_tornozelo_y', models.FloatField(blank=True, null=True)),
                ('esq_angulo_perna', models.FloatField(blank=True, null=True)),
                ('dir_angulo_perna', models.FloatField(blank=True, null=True)),
                ('perna_da_frente', models.CharField(blank=True, max_length=50, null=True)),
                ('pulso_da_frente', models.CharField(blank=True, max_length=50, null=True)),
                ('copo_acima', models.BooleanField(default=False)),
                ('stretch_pe_arma', models.BooleanField(default=False)),
            ],
        ),
    ]
